# Generated by Django 4.2.25 on 2026-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_round_unique_together_remove_round_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=120, help_text='How long this round stays open once it starts.'),
        ),
        migrations.AddField(
            model_name='round',
            name='starts_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Set automatically when this round becomes current. Leave blank.', null=True),
        ),
    ]
