# Generated by Django 4.2.25 on 2026-09-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_round_duration_seconds_round_starts_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='current_lobby',
        ),
        migrations.AddField(
            model_name='game',
            name='player_limit',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='safety_buffer',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed')], default='REGISTRATION', max_length=20),
        ),
        migrations.AddField(
            model_name='lobby',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='lobby',
            unique_together={('game', 'sequence_number')},
        ),
        migrations.CreateModel(
            name='GameMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('eligible_from_round', models.PositiveIntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='game.game')),
                ('lobby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='game.lobby')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='game.participant')),
            ],
            options={
                'unique_together': {('game', 'participant')},
            },
        ),
    ]
