# Generated by Django 4.2.25 on 2026-09-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_game_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='safety_buffer',
        ),
    ]
